# Generated by Django 3.1.2 on 2021-04-06 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (), 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
