# Generated by Django 3.1.2 on 2021-04-06 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0002_auto_20210406_1746'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'default_permissions': (), 'ordering': ['-id'], 'permissions': (('view_departamento', 'Can view Departamento'), ('add_departamento', 'Can add Departamento'), ('change_departamento', 'Can change Departamento'), ('delete_departamento', 'Can delete Departamento')), 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
