# Generated by Django 3.1.2 on 2021-04-06 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0003_auto_20210406_1751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('denominacion', models.CharField(max_length=50, verbose_name='Denominacion')),
            ],
            options={
                'verbose_name': 'Distrito',
                'verbose_name_plural': 'Distritos',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Seccional',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod', models.IntegerField(unique=True)),
                ('denominacion', models.CharField(max_length=50, verbose_name='Denominacion')),
            ],
            options={
                'verbose_name': 'Seccional',
                'verbose_name_plural': 'Seccionales',
                'ordering': ['-id'],
            },
        ),
    ]
