# Generated by Django 3.1.2 on 2021-04-06 23:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0004_distrito_seccional'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='departamento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='electoral.departamento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seccional',
            name='distrito',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='electoral.distrito'),
            preserve_default=False,
        ),
    ]
