# Generated by Django 3.1.2 on 2021-04-07 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0006_elector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elector',
            name='distrito',
        ),
        migrations.RemoveField(
            model_name='elector',
            name='seccional',
        ),
    ]
