# Generated by Django 3.1.2 on 2021-04-07 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0007_auto_20210406_2025'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='distrito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electoral.distrito'),
        ),
        migrations.AddField(
            model_name='elector',
            name='seccional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electoral.seccional', to_field='cod'),
        ),
    ]
