# Generated by Django 3.1.2 on 2021-04-07 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0008_auto_20210406_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='voto4',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
