# Generated by Django 3.1.2 on 2021-04-07 01:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0009_elector_voto4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='seccional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electoral.seccional'),
        ),
    ]
