# Generated by Django 3.1.2 on 2021-04-07 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0010_auto_20210406_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='ci',
            field=models.IntegerField(null=True),
        ),
    ]
