# Generated by Django 3.1.2 on 2021-04-07 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0011_auto_20210406_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='fecha_afiliacion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='elector',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
    ]
