# Generated by Django 3.1.2 on 2021-04-10 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0013_barrio_ciudad_manzana'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barrio',
            name='ciudad',
        ),
        migrations.DeleteModel(
            name='Manzana',
        ),
        migrations.DeleteModel(
            name='Barrio',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
    ]
