# Generated by Django 3.1.2 on 2021-04-10 22:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0015_barrio_ciudad_manzana'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzana',
            name='barrio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='electoral.barrio'),
            preserve_default=False,
        ),
    ]
