# Generated by Django 3.1.2 on 2021-04-11 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0016_manzana_barrio'),
    ]

    operations = [
        migrations.AddField(
            model_name='manzana',
            name='cod',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
