# Generated by Django 3.1.2 on 2021-04-11 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0018_auto_20210410_2044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manzana',
        ),
    ]
