# Generated by Django 3.1.2 on 2021-04-11 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0020_manzana'),
    ]

    operations = [
        migrations.CreateModel(
            name='Padgral',
            fields=[
                ('mesa', models.CharField(blank=True, max_length=3, null=True)),
                ('orden', models.CharField(blank=True, max_length=5, null=True)),
                ('numero_ced', models.DecimalField(decimal_places=0, max_digits=15, primary_key=True, serialize=False)),
                ('apellido', models.CharField(blank=True, max_length=80, null=True)),
                ('nombre', models.CharField(blank=True, max_length=80, null=True)),
                ('fecha_naci', models.DateField(blank=True, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('estado', models.CharField(blank=True, max_length=1, null=True)),
                ('n_partido', models.CharField(blank=True, max_length=200, null=True)),
                ('cod_seccional', models.CharField(blank=True, max_length=3, null=True)),
                ('voto_19', models.CharField(blank=True, max_length=1, null=True)),
                ('voto_23', models.CharField(blank=True, max_length=1, null=True)),
                ('voto_1911', models.CharField(blank=True, max_length=1, null=True)),
                ('voto_1612', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_barrio', models.CharField(blank=True, max_length=5, null=True)),
                ('cod_manzana', models.CharField(blank=True, max_length=5, null=True)),
                ('nro_casa', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
                ('cod_lugar', models.CharField(blank=True, max_length=5, null=True)),
                ('voto', models.CharField(blank=True, max_length=1, null=True)),
                ('nro_telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('referencia', models.CharField(blank=True, max_length=50, null=True)),
                ('pasoxpc', models.CharField(blank=True, max_length=1, null=True)),
                ('pasoxmv', models.CharField(blank=True, max_length=1, null=True)),
                ('cod_dpto', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_dist', models.CharField(blank=True, max_length=3, null=True)),
                ('codigo_sex', models.CharField(blank=True, max_length=1, null=True)),
                ('voto_2003', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'padgral',
            },
        ),
    ]
