# Generated by Django 3.1.2 on 2021-04-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0022_auto_20210410_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='barrio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electoral.barrio'),
        ),
        migrations.AddField(
            model_name='elector',
            name='manzana',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='electoral.manzana'),
        ),
        migrations.AddField(
            model_name='elector',
            name='nro_casa',
            field=models.IntegerField(null=True),
        ),
    ]
