# Generated by Django 3.1.2 on 2021-04-12 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0023_auto_20210410_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='nro_casa',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
