# Generated by Django 3.1.2 on 2021-04-12 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0024_auto_20210412_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='telefono',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
