# Generated by Django 3.1.2 on 2021-04-12 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0026_auto_20210412_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrio',
            options={'ordering': ['ciudad', 'denominacion'], 'verbose_name': 'Barrio', 'verbose_name_plural': 'Barrios'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'ordering': ['denominacion'], 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['denominacion'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='distrito',
            options={'ordering': ['departamento', 'denominacion'], 'verbose_name': 'Distrito', 'verbose_name_plural': 'Distritos'},
        ),
        migrations.AlterModelOptions(
            name='manzana',
            options={'ordering': ['barrio', 'denominacion'], 'verbose_name': 'Manzana', 'verbose_name_plural': 'Manzanas'},
        ),
        migrations.AlterModelOptions(
            name='seccional',
            options={'ordering': ['distrito', 'denominacion'], 'verbose_name': 'Seccional', 'verbose_name_plural': 'Seccionales'},
        ),
    ]
