# Generated by Django 3.1.2 on 2021-04-13 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0027_auto_20210412_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elector2',
            fields=[
            ],
            options={
                'verbose_name': 'Electores Barrio Manzana',
                'verbose_name_plural': 'Electores Barrio Manzanas',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('electoral.elector',),
        ),
        migrations.AlterModelOptions(
            name='elector',
            options={'verbose_name': 'Elector', 'verbose_name_plural': 'Electores'},
        ),
    ]
