# Generated by Django 3.1.2 on 2021-04-15 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electoral', '0028_auto_20210413_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='fecha_afiliacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='elector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
    ]
